[package]
name = "gito"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.7"
regex = "1"
open = "2.1.1"
reqwest = "0.11.10"
tokio = { version = "1.9", features = ["full"] }
